export const GET_ALL_MOVIE_REQUEST = 'GET_ALL_MOVIE_REQUEST';
export const GET_ALL_MOVIE_SUCCESS = 'GET_ALL_MOVIE_SUCCESS';
export const GET_ALL_MOVIE_FAILED = 'GET_ALL_MOVIE_FAILED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'GET_ALL_MOVIE_FAILED';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const GET_ALL_CENIMA_SYSTEM_SUCCESS = 'GET_ALL_CENIMA_SYSTEM_SUCCESS';
export const GET_ALL_INFO_CINEMA_SUCCESS = 'GET_ALL_INFO_CINEMA_SUCCESS'
export const GET_ALL_SHOW_TIME_CINEMA_SUCCESS = 'GET_ALL_SHOW_TIME_CINEMA_SUCCESS'
export const GET_ALL_CENIMA_HOMETOOL_SUCCESS = 'GET_ALL_CENIMA_HOMETOOL_SUCCESS';
export const GET_ALL_CINEMA_DAY = 'GET_ALL_CINEMA_DAY';
export const GET_SHOW_SHEDULE_INFO_SUCCESS = 'GET_SHOW_SHEDULE_INFO_SUCCESS';

export const GET_DETAIL_MOVIE_REQUEST = 'GET_DETAIL_MOVIE_REQUEST';
export const GET_DETAIL_MOVIE_SUCCESS = 'GET_DETAIL_MOVIE_SUCCESS';
export const GET_DETAIL_MOVIE_FAILED = 'GET_DETAIL_MOVIE_FAILED';

export const GET_TICKER_ROOMS_SUCCESS = 'GET_TICKER_ROOMS_SUCCESS'

